# Generated by Django 5.1 on 2024-08-28 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_room_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
